### ISSUE TITLE
Error when setting the clubroom state after cold boot

### ISSUE THREAD

**Issue by Diftraku** [Diftraku/cortana2#6]
```
 02:11:57 <Cortana> IndexError: no such group (file "/home/sopel/cortana2/modules/cortana.py", line 43, in set_clubroom_status)
```

Related to #2

**Comment by Diftraku** [comment]
More specific error that popped up after fixing the initial state handling at boot
```
Traceback (most recent call last):
  File "/scratch/cortana2/.pyenv/lib64/python3.7/site-packages/sopel/tools/jobs.py", line 142, in _call
    func(self.bot)
  File "/scratch/cortana2/modules/cortana.py", line 123, in sync_presence_timer
    sync_channel_topic(bot, channel)
  File "/scratch/cortana2/modules/cortana.py", line 136, in sync_channel_topic
    topic = bot.channels[channel].topic.split(TOPIC_SEPARATOR)
KeyError: '#channel'
```
